version: "3"
services:
  express_server:
    build: .
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 5000:5000
    networks:
      - mern-app
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
